name: my_iap_package
description: "A lightweight, framework-agnostic wrapper for in_app_purchase with support for subscriptions and lifetime purchases."
version: 1.1.0+1
homepage:

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
